-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 21:00:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `data_management` ;

-- -----------------------------------------------------
-- Schema data_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_management` DEFAULT CHARACTER SET utf8 ;
USE `data_management` ;

-- -----------------------------------------------------
-- Table `data_management`.`constituencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_management`.`constituencies` ;

CREATE TABLE IF NOT EXISTS `data_management`.`constituencies` (
  `constituencies_id` INT(11) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `Members of Parliament name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`constituencies_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_management`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_management`.`station` ;

CREATE TABLE IF NOT EXISTS `data_management`.`station` (
  `site_id` INT(5) NOT NULL,
  `site name` VARCHAR(45) NULL,
  `longitude` FLOAT(20) NULL,
  `latitude` FLOAT(20) NULL,
  `constituencies_id_fk` INT(11) NOT NULL,
  PRIMARY KEY (`site_id`),
  CONSTRAINT `fk_station_constituencies1`
    FOREIGN KEY (`constituencies_id_fk`)
    REFERENCES `data_management`.`constituencies` (`constituencies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_management`.`schema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_management`.`schema` ;

CREATE TABLE IF NOT EXISTS `data_management`.`schema` (
  `masure` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_management`.`read`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_management`.`read` ;

CREATE TABLE IF NOT EXISTS `data_management`.`read` (
  `datetime` DATETIME NOT NULL,
  `site_id_fk` INT(5) NULL,
  `NOx` FLOAT(20) NULL,
  `NO2` FLOAT(20) NULL,
  `NO` FLOAT(20) NULL,
  `pm10` FLOAT(20) NULL,
  `O3` FLOAT(20) NULL,
  `Temperature` FLOAT NULL,
  `objectid` INT(11) NULL,
  `objectid2` INT(10) NOT NULL,
  `NVPM10` FLOAT(20) NULL,
  `VPM10` FLOAT(20) NULL,
  `nvpm2.5` INT NULL,
  `PM2.5` FLOAT(20) NULL,
  `VPM2.5` FLOAT(20) NULL,
  `CO` FLOAT(20) NULL,
  `RH` FLOAT(20) NULL,
  `Pressure` FLOAT(20) NULL,
  `SO2` FLOAT(20) NULL,
  PRIMARY KEY (`objectid2`),
  CONSTRAINT `fk_read_station`
    FOREIGN KEY (`site_id_fk`)
    REFERENCES `data_management`.`station` (`site_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
